In [1]:
import numpy as np

- Pressing `Tab` will provide autocomplete suggestions. For example type `np.` and press Tab to see get a list with available methods.
- Pressing `Shift + Tab` will provide info for a given method. For example type `np.absolute` and press Shift + Tab to get info window of what the method does.

In [2]:
# Create numpy list based on a python list

my_list = [1, 2, 3]
print(type(my_list)) # <class 'list'>

my_np_list = np.array(my_list)
print(type(my_np_list)) # <class 'numpy.ndarray'>

<class 'list'>
<class 'numpy.ndarray'>


In [3]:
# Create list using built-in methods

np.arange(0, 10, 2) # array([0, 2, 4, 6, 8])

array([0, 2, 4, 6, 8])

In [4]:
# Create matrix filled with zero floating numbers

np.zeros((2, 3))
# array([[0., 0., 0.],
#       [0., 0., 0.]])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# Important difference between numpy array and python array is that numpy supports broadcasting
# Using broadcasting we can reassign multiple values at once
nums_list = np.array([1, 2, 3, 4, 5])
nums_list[0:2] = 9
nums_list

array([9, 9, 3, 4, 5])

In [6]:
# Some more advanced selections
nums_arr_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Below 2 lines will produce the same result
print(nums_arr_matrix[1][1]) # 5
print(nums_arr_matrix[1,1]) # 5
nums_arr_matrix[:2, 1:] # take the first 2 elements and from them take everything starting from the second element

5
5


array([[2, 3],
       [5, 6]])

In [7]:
# Conditional selection
full_list = np.arange(1, 11)
odd_list = full_list[full_list % 2 != 0]
odd_list

array([1, 3, 5, 7, 9])